# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml
# Or use the DigitalOcean web console

name: tai-platform-api
region: nyc

services:
  - name: api
    github:
      repo: seludoto/TAI
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: pip install -r requirements.txt
    
    # Run configuration
    run_command: gunicorn main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --workers 2
    
    # Use Dockerfile for build
    dockerfile_path: Dockerfile
    
    # Environment variables
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${db.DATABASE_URL}
      
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: your-production-secret-key-change-this
      
      - key: AI_PROVIDER
        scope: RUN_TIME
        value: digitalocean
      
      - key: DIGITALOCEAN_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: sk-do-rm5p4ChxhK80oTytq2zMfbmymFQ98lASYcekdFR35NJqei31QcFTjfbA6t
      
      - key: ALLOWED_ORIGINS
        scope: RUN_TIME
        value: "*"
      
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 8000
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Auto-scaling (optional)
    autoscaling:
      min_instance_count: 1
      max_instance_count: 3
      metrics:
        cpu:
          percent: 80

# Database (PostgreSQL)
databases:
  - name: db
    engine: PG
    production: false
    version: "15"
